# initialize image
FROM debian:bookworm

# install nginx
RUN apt-get update && \
    apt-get install -y nginx

# install php-fpm
RUN apt-get install -y php8.1 php8.1-common php-pear php8.1-mbstring php8.1-fpm
RUN apt-get install -y php8.1-gd php8.1-intl php8.1-soap php8.1-curl php8.1-mysql

LABEL maintainer="anuws505"
LABEL version="1.0"
LABEL description="A PHP and Nginx on Debain 12"

RUN mkdir /opt/certs
COPY certs/. /opt/certs/.
COPY etc_nginx_sites-available_default /etc/nginx/sites-available/default
COPY code/. /var/www/html/.
RUN chown -R www-data:www-data /var/www/html
# -- or when default root dir --
# RUN chmod 777 /var/www/html/var
# RUN chmod 777 /var/www/html/app/etc
# RUN chmod 777 /var/www/html/media
# RUN chmod 777 /var/www/html/media/customer
# RUN chmod 777 /var/www/html/media/dhl
# RUN chmod 777 /var/www/html/media/dhl/logo.jpg
# RUN chmod 777 /var/www/html/media/downloadable

EXPOSE 80/tcp
EXPOSE 443/tcp

# CMD ["/bin/bash", "-c", "nginx -g 'daemon off;'"]
CMD ["/bin/bash", "-c", "service php8.1-fpm start && nginx -g 'daemon off;' && nginx -s reload"]